- hosts: all
  vars:
    redmine_port: 3000
    REDMINE_DB_POSTGRES: master.72914ab7-8cfa-4de8-bfe1-eee20af15184.c.dbaas.selcloud.ru
    REDMINE_DB_DATABASE: Hexlet
    REDMINE_DB_USERNAME: emma
    REDMINE_DB_PORT: 5432
  vars_files:
    - group_vars/webservers/vault.yml
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
  tasks:
    - name: Create .env file
      ansible.builtin.template:
        src: .env.j2
        dest: .env
      tags: deploy

    - name: Deploy redmine
      community.docker.docker_container:
        name: redmine
        image: "redmine:latest"
        restart_policy: always
        state: started
        env_file: .env
        ports: "3000:3000"
      tags: deploy