- hosts: all
  gather_facts: no
  tasks:
    - name: Install pip's docker 
      pip: 
        name: docker
      tags: req

    - name: Copy .env
      ansible.builtin.template:
        src: templates/.env
        dest: .env

    - name: Deploy Redmine
      community.docker.docker_container:
        name: redmine
        image: "redmine:latest"
        restart_policy: always
        state: started
        env_file: .env
        ports: "3000:3000"
      tags: deploy
