- hosts: all
  vars_files:
    - group_vars/webservers/vars.yml
    - group_vars/webservers/vault.yml
  roles:
    - role: geerlingguy.pip
      vars:
        pip_install_packages:
          - name: docker
  tasks:
    - name: Create .env file
      ansible.builtin.template:
        src: .env.j2
        dest: .env
      tags: deploy

    - name: Deploy redmine
      community.docker.docker_container:
        name: redmine
        image: "redmine:latest"
        restart_policy: always
        state: started
        env_file: .env
        ports: "3000:3000"
      tags: deploy