- name: Hexlet Task 2
  hosts: all
  gather_facts: false
  tasks:
    - name: Install pip's docker
      ansible.builtin.pip:
        name: docker
      tags: req

    - name: Copy .env
      ansible.builtin.template:
        src: templates/.env
        dest: .env
        mode: '0644'
        owner: root
        group: root
      become: true

    - name: Deploy Redmine
      community.docker.docker_container:
        name: redmine
        image: "redmine:latest"
        restart_policy: always
        state: started
        env_file: .env
        ports: "3007:3007"
      tags: deploy
